### ISSUE TITLE
api issue

### ISSUE THREAD

**Issue by cheeth** [dsebastien/youtubeChannelVideosFinder#2]
Hi, I love your application, I'm keen to try it out. What kind of API key do I need. Do I need a server API then use my computers IP address to register it. I'm a little confused in this area.

Please help me to understand this part, 

Best wishes,
Paul

**Comment by dsebastien** [comment]
Hey Paul,

You can get an API key from there: https://console.developers.google.com

**Comment by cheeth** [comment]
Thanks for the quick response, I seen that. I'm just not sure of which API I need? Looks like I need to enter an IP address for a server to get the API. Sorry if this is an obvious question.

**Comment by cheeth** [comment]
I mean this part here http://d.pr/i/1bhVS

**Comment by cheeth** [comment]
I think I've got an API key, I was confused by the optional field, it's only needed if you want to restrict access to a specific app, or IP.

**Comment by cheeth** [comment]
closing

**Comment by dsebastien** [comment]
Good news. Enjoy ;-)
